/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IMF Backend
 * IMF Backend
 * OpenAPI spec version: 0.1.0
 */
import { api } from "../../instance";
import type {
  OauthCallbackApiV0AuthProviderCallbackGetParams,
  ResponseLogin,
} from "./iMFBackend.schemas";

/**
 * @summary Oauth Login
 */
export const oauthLoginApiV0AuthProviderLoginGet = (provider: string) => {
  return api<unknown>({ url: `/api/v0/auth/${provider}/login`, method: "GET" });
};
/**
 * @summary Oauth Callback
 */
export const oauthCallbackApiV0AuthProviderCallbackGet = (
  provider: string,
  params: OauthCallbackApiV0AuthProviderCallbackGetParams,
) => {
  return api<ResponseLogin>({
    url: `/api/v0/auth/${provider}/callback`,
    method: "GET",
    params,
  });
};
export type OauthLoginApiV0AuthProviderLoginGetResult = NonNullable<
  Awaited<ReturnType<typeof oauthLoginApiV0AuthProviderLoginGet>>
>;
export type OauthCallbackApiV0AuthProviderCallbackGetResult = NonNullable<
  Awaited<ReturnType<typeof oauthCallbackApiV0AuthProviderCallbackGet>>
>;
