/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IMF Backend
 * IMF Backend
 * OpenAPI spec version: 0.1.0
 */
import { api } from "../../instance";
import type {
  CheckContactNumberApiV0ContactCheckGetParams,
  ContactListResponse,
  CreateContactRequest,
  CreateContactResponse,
} from "./iMFBackend.schemas";

/**
 * @summary Get Contact List
 */
export const getContactListApiV0ContactGet = () => {
  return api<ContactListResponse>({ url: `/api/v0/contact`, method: "GET" });
};
/**
 * @summary Get Contact List
 */
export const getContactListApiV0ContactPost = (
  createContactRequest: CreateContactRequest,
) => {
  return api<CreateContactResponse>({
    url: `/api/v0/contact`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createContactRequest,
  });
};
/**
 * @summary Check Contact Number
 */
export const checkContactNumberApiV0ContactCheckGet = (
  params: CheckContactNumberApiV0ContactCheckGetParams,
) => {
  return api<CreateContactResponse>({
    url: `/api/v0/contact/check`,
    method: "GET",
    params,
  });
};
export type GetContactListApiV0ContactGetResult = NonNullable<
  Awaited<ReturnType<typeof getContactListApiV0ContactGet>>
>;
export type GetContactListApiV0ContactPostResult = NonNullable<
  Awaited<ReturnType<typeof getContactListApiV0ContactPost>>
>;
export type CheckContactNumberApiV0ContactCheckGetResult = NonNullable<
  Awaited<ReturnType<typeof checkContactNumberApiV0ContactCheckGet>>
>;
