/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IMF Backend
 * IMF Backend
 * OpenAPI spec version: 0.1.0
 */
import { api } from "../../instance";
import type { HealthCheckHealthGet200 } from "./iMFBackend.schemas";

/**
 * Health Check API
 * @summary Health Check
 */
export const healthCheckHealthGet = () => {
  return api<HealthCheckHealthGet200>({ url: `/health`, method: "GET" });
};
