/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IMF Backend
 * IMF Backend
 * OpenAPI spec version: 0.1.0
 */
import { api } from "../../instance";
import type {
  GetMatchListApiV0MatchGetParams,
  MatchDetailResponse,
  MatchListResponse,
  MatchingRespondRequest,
  ResponseBaseModel,
} from "./iMFBackend.schemas";

/**
 * @summary Get Match List
 */
export const getMatchListApiV0MatchGet = (
  params: GetMatchListApiV0MatchGetParams,
) => {
  return api<MatchListResponse>({
    url: `/api/v0/match`,
    method: "GET",
    params,
  });
};
/**
 * @summary Get Recommed Match List
 */
export const getRecommedMatchListApiV0MatchRecommendGet = () => {
  return api<MatchListResponse>({
    url: `/api/v0/match/recommend`,
    method: "GET",
  });
};
/**
 * @summary Get Match Detail
 */
export const getMatchDetailApiV0MatchMatchIdGet = (matchId: number) => {
  return api<MatchDetailResponse>({
    url: `/api/v0/match/${matchId}`,
    method: "GET",
  });
};
/**
 * @summary Respond To Match
 */
export const respondToMatchApiV0MatchMatchIdPatch = (
  matchId: number,
  matchingRespondRequest: MatchingRespondRequest,
) => {
  return api<ResponseBaseModel>({
    url: `/api/v0/match/${matchId}`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: matchingRespondRequest,
  });
};
export type GetMatchListApiV0MatchGetResult = NonNullable<
  Awaited<ReturnType<typeof getMatchListApiV0MatchGet>>
>;
export type GetRecommedMatchListApiV0MatchRecommendGetResult = NonNullable<
  Awaited<ReturnType<typeof getRecommedMatchListApiV0MatchRecommendGet>>
>;
export type GetMatchDetailApiV0MatchMatchIdGetResult = NonNullable<
  Awaited<ReturnType<typeof getMatchDetailApiV0MatchMatchIdGet>>
>;
export type RespondToMatchApiV0MatchMatchIdPatchResult = NonNullable<
  Awaited<ReturnType<typeof respondToMatchApiV0MatchMatchIdPatch>>
>;
