/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * IMF Backend
 * IMF Backend
 * OpenAPI spec version: 0.1.0
 */
import { api } from "../../instance";
import type {
  BodyGetTokenApiV0UsersLoginUserIdTestPost,
  BodyUploadUserProfileImageApiV0UsersImagesPost,
  MatchingSettingRequest,
  RequestImgThumbnail,
  RequestSignupDto,
  RequestVerficationCode,
  RequestVerificationDto,
  ResponseBaseModel,
  ResponseImgList,
  ResponseSingleImg,
  ResponseUserContact,
  ResponseUserInfo,
  ResponseUserMatchingSetting,
  ResponseUserProfile,
  ResponseVerifcationCode,
  UserContactDto,
  UserProfileDto,
  UserProfileUpdateDto,
  VerificationResultResponse,
} from "./iMFBackend.schemas";

/**
 * @summary Get Is Match Possible
 */
export const getIsMatchPossibleApiV0UsersMatchingSettingsPatch = (
  matchingSettingRequest: MatchingSettingRequest,
) => {
  return api<ResponseUserMatchingSetting>({
    url: `/api/v0/users/matching-settings`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: matchingSettingRequest,
  });
};
/**
 * @summary Get User Profile
 */
export const getUserProfileApiV0UsersProfileGet = () => {
  return api<ResponseUserProfile>({
    url: `/api/v0/users/profile`,
    method: "GET",
  });
};
/**
 * @summary Create User Profile
 */
export const createUserProfileApiV0UsersProfilePost = (
  userProfileDto: UserProfileDto,
) => {
  return api<ResponseBaseModel>({
    url: `/api/v0/users/profile`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: userProfileDto,
  });
};
/**
 * @summary Update User Profile
 */
export const updateUserProfileApiV0UsersProfilePatch = (
  userProfileUpdateDto: UserProfileUpdateDto,
) => {
  return api<ResponseBaseModel>({
    url: `/api/v0/users/profile`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: userProfileUpdateDto,
  });
};
/**
 * @summary Get Verrify
 */
export const getVerrifyApiV0UsersVerificationGet = () => {
  return api<unknown>({ url: `/api/v0/users/verification`, method: "GET" });
};
/**
 * @summary Request Verification
 */
export const requestVerificationApiV0UsersVerificationPost = (
  requestVerificationDto: RequestVerificationDto,
) => {
  return api<VerificationResultResponse>({
    url: `/api/v0/users/verification`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: requestVerificationDto,
  });
};
/**
 * @summary Get User Contact Profile
 */
export const getUserContactProfileApiV0UsersContactGet = () => {
  return api<ResponseUserContact>({
    url: `/api/v0/users/contact`,
    method: "GET",
  });
};
/**
 * @summary Create User Contact Profile
 */
export const createUserContactProfileApiV0UsersContactPut = (
  userContactDto: UserContactDto,
) => {
  return api<ResponseBaseModel>({
    url: `/api/v0/users/contact`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: userContactDto,
  });
};
/**
 * @summary Get User Profile Images
 */
export const getUserProfileImagesApiV0UsersImagesGet = () => {
  return api<ResponseImgList>({ url: `/api/v0/users/images`, method: "GET" });
};
/**
 * @summary Upload User Profile Image
 */
export const uploadUserProfileImageApiV0UsersImagesPost = (
  bodyUploadUserProfileImageApiV0UsersImagesPost: BodyUploadUserProfileImageApiV0UsersImagesPost,
) => {
  const formData = new FormData();
  formData.append(`file`, bodyUploadUserProfileImageApiV0UsersImagesPost.file);

  return api<ResponseSingleImg>({
    url: `/api/v0/users/images`,
    method: "POST",
    headers: { "Content-Type": "multipart/form-data" },
    data: formData,
  });
};
/**
 * @summary Delete User Profile Image
 */
export const deleteUserProfileImageApiV0UsersImagesDelete = (
  requestImgThumbnail: RequestImgThumbnail,
) => {
  return api<ResponseBaseModel>({
    url: `/api/v0/users/images`,
    method: "DELETE",
    headers: { "Content-Type": "application/json" },
    data: requestImgThumbnail,
  });
};
/**
 * @summary Setting Thumbnail
 */
export const settingThumbnailApiV0UsersImagesPatch = (
  requestImgThumbnail: RequestImgThumbnail,
) => {
  return api<ResponseBaseModel>({
    url: `/api/v0/users/images`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: requestImgThumbnail,
  });
};
/**
 * @summary Create Verfication Code
 */
export const createVerficationCodeApiV0UsersVerificationCodesPost = (
  requestVerficationCode: RequestVerficationCode,
) => {
  return api<ResponseVerifcationCode>({
    url: `/api/v0/users/verification-codes`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: requestVerficationCode,
  });
};
/**
 * @summary Add User
 */
export const addUserApiV0UsersSignupPost = (
  requestSignupDto: RequestSignupDto,
) => {
  return api<ResponseBaseModel>({
    url: `/api/v0/users/signup`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: requestSignupDto,
  });
};
/**
 * @summary Get User
 */
export const getUserApiV0UsersGet = () => {
  return api<ResponseUserInfo>({ url: `/api/v0/users`, method: "GET" });
};
/**
 * @summary Get Token
 */
export const getTokenApiV0UsersLoginUserIdTestPost = (
  bodyGetTokenApiV0UsersLoginUserIdTestPost: BodyGetTokenApiV0UsersLoginUserIdTestPost,
) => {
  const formUrlEncoded = new URLSearchParams();
  formUrlEncoded.append(
    `user_id`,
    bodyGetTokenApiV0UsersLoginUserIdTestPost.user_id.toString(),
  );

  return api<unknown>({
    url: `/api/v0/users/login/user_id/test`,
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    data: formUrlEncoded,
  });
};
export type GetIsMatchPossibleApiV0UsersMatchingSettingsPatchResult =
  NonNullable<
    Awaited<
      ReturnType<typeof getIsMatchPossibleApiV0UsersMatchingSettingsPatch>
    >
  >;
export type GetUserProfileApiV0UsersProfileGetResult = NonNullable<
  Awaited<ReturnType<typeof getUserProfileApiV0UsersProfileGet>>
>;
export type CreateUserProfileApiV0UsersProfilePostResult = NonNullable<
  Awaited<ReturnType<typeof createUserProfileApiV0UsersProfilePost>>
>;
export type UpdateUserProfileApiV0UsersProfilePatchResult = NonNullable<
  Awaited<ReturnType<typeof updateUserProfileApiV0UsersProfilePatch>>
>;
export type GetVerrifyApiV0UsersVerificationGetResult = NonNullable<
  Awaited<ReturnType<typeof getVerrifyApiV0UsersVerificationGet>>
>;
export type RequestVerificationApiV0UsersVerificationPostResult = NonNullable<
  Awaited<ReturnType<typeof requestVerificationApiV0UsersVerificationPost>>
>;
export type GetUserContactProfileApiV0UsersContactGetResult = NonNullable<
  Awaited<ReturnType<typeof getUserContactProfileApiV0UsersContactGet>>
>;
export type CreateUserContactProfileApiV0UsersContactPutResult = NonNullable<
  Awaited<ReturnType<typeof createUserContactProfileApiV0UsersContactPut>>
>;
export type GetUserProfileImagesApiV0UsersImagesGetResult = NonNullable<
  Awaited<ReturnType<typeof getUserProfileImagesApiV0UsersImagesGet>>
>;
export type UploadUserProfileImageApiV0UsersImagesPostResult = NonNullable<
  Awaited<ReturnType<typeof uploadUserProfileImageApiV0UsersImagesPost>>
>;
export type DeleteUserProfileImageApiV0UsersImagesDeleteResult = NonNullable<
  Awaited<ReturnType<typeof deleteUserProfileImageApiV0UsersImagesDelete>>
>;
export type SettingThumbnailApiV0UsersImagesPatchResult = NonNullable<
  Awaited<ReturnType<typeof settingThumbnailApiV0UsersImagesPatch>>
>;
export type CreateVerficationCodeApiV0UsersVerificationCodesPostResult =
  NonNullable<
    Awaited<
      ReturnType<typeof createVerficationCodeApiV0UsersVerificationCodesPost>
    >
  >;
export type AddUserApiV0UsersSignupPostResult = NonNullable<
  Awaited<ReturnType<typeof addUserApiV0UsersSignupPost>>
>;
export type GetUserApiV0UsersGetResult = NonNullable<
  Awaited<ReturnType<typeof getUserApiV0UsersGet>>
>;
export type GetTokenApiV0UsersLoginUserIdTestPostResult = NonNullable<
  Awaited<ReturnType<typeof getTokenApiV0UsersLoginUserIdTestPost>>
>;
